name: iwv_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.3.1
  flutter_callkit_incoming: ^2.0.4

flutter:
  uses-material-design: true
